apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami   # repo Helm
    chart: redis
    targetRevision: "22.0.7"                      # versión del chart

    # <-- Aquí va la sección helm
    helm:
      valueFiles:
        - apps/redis/values/values-dev.yaml       # ruta relativa dentro del repo

  destination:
    server: https://kubernetes.default.svc
    namespace: redis-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
