apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lorenaestela423-coder/argocd_practicas.git
    path: path/dentro/de/tu/repo    # <-- Aquí va el path a los manifests de Kubernetes
    targetRevision: main             # <-- Rama o commit que quieras usar
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
