apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      trace_idle_period: 10s
      max_block_duration: 5m

    compactor:
      compaction:
        compacted_block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces   # Aquí va el PVC
