apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-loki-dirs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /loki/index /loki/chunks /loki/boltdb-shipper-compactor']
        volumeMounts:
        - name: loki-storage
          mountPath: /loki
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
          - -config.file=/etc/loki/local-config.yaml
        ports:
          - containerPort: 3100
        volumeMounts:
          - name: loki-storage
            mountPath: /loki
          - name: loki-config
            mountPath: /etc/loki/local-config.yaml
            subPath: local-config.yaml
      volumes:
      - name: loki-storage
        emptyDir: {}
      - name: loki-config
        configMap:
          name: loki-config
