apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
          - -config.file=/etc/loki/local-config.yaml
        volumeMounts:
          - name: loki-data
            mountPath: /loki   # aquí Loki escribirá datos
      volumes:
      - name: loki-data
        emptyDir: {}
