apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lorenaestela423-coder/argocd_practicas.git
    path: observability-gitops/ingress
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
